version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
     - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
  ingestion:
      image: kafka-docker_ingestion
      depends_on: 
      - "kafka"
      ports: 
       - "5000:5000"
  batchlayer:
      build: .
      depends_on: 
      - "kafka"
      ports: 
      - "5001:5001"