version: "2"
services: 
    spark-app:
        image: bde/spark-app
        container_name: spark-app
        environment: 
            - "SPARK_MASTER=spark://spark-master:7077"
            - INIT_DAEMON_STEP=false
        depends_on:
            - spark-master
networks:
    default:
        external:
            name: kafka-network